package cpp.Absyn; // Java Package generated by the BNF Converter.

public class ADeclInit extends Arg {
  public final Type type_;
  public ADeclInit(Type p1) { type_ = p1; }

  public <R,A> R accept(cpp.Absyn.Arg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof cpp.Absyn.ADeclInit) {
      cpp.Absyn.ADeclInit x = (cpp.Absyn.ADeclInit)o;
      return this.type_.equals(x.type_);
    }
    return false;
  }

  public int hashCode() {
    return this.type_.hashCode();
  }


}
