package cpp.Absyn; // Java Package generated by the BNF Converter.

public class ADecl extends Arg {
  public final Type type_;
  public final Var var_;
  public ADecl(Type p1, Var p2) { type_ = p1; var_ = p2; }

  public <R,A> R accept(cpp.Absyn.Arg.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof cpp.Absyn.ADecl) {
      cpp.Absyn.ADecl x = (cpp.Absyn.ADecl)o;
      return this.type_.equals(x.type_) && this.var_.equals(x.var_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(this.type_.hashCode())+this.var_.hashCode();
  }


}
