package cpp.Absyn; // Java Package generated by the BNF Converter.

public abstract class Def implements java.io.Serializable {
  public abstract <R,A> R accept(Def.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(cpp.Absyn.DFun p, A arg);
    public R visit(cpp.Absyn.DFunBody p, A arg);
    public R visit(cpp.Absyn.DUsing p, A arg);
    public R visit(cpp.Absyn.DInit p, A arg);
    public R visit(cpp.Absyn.DTD p, A arg);

  }

}
