package cpp.Absyn; // Java Package generated by the BNF Converter.

public class DFunBody extends Def {
  public final Type type_;
  public final String id_;
  public final ListArg listarg_;
  public DFunBody(Type p1, String p2, ListArg p3) { type_ = p1; id_ = p2; listarg_ = p3; }

  public <R,A> R accept(cpp.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof cpp.Absyn.DFunBody) {
      cpp.Absyn.DFunBody x = (cpp.Absyn.DFunBody)o;
      return this.type_.equals(x.type_) && this.id_.equals(x.id_) && this.listarg_.equals(x.listarg_);
    }
    return false;
  }

  public int hashCode() {
    return 37*(37*(this.type_.hashCode())+this.id_.hashCode())+this.listarg_.hashCode();
  }


}
