package cpp.Absyn; // Java Package generated by the BNF Converter.

public abstract class PType implements java.io.Serializable {
  public abstract <R,A> R accept(PType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(cpp.Absyn.Tbool p, A arg);
    public R visit(cpp.Absyn.Tdouble p, A arg);
    public R visit(cpp.Absyn.Tint p, A arg);
    public R visit(cpp.Absyn.Tvoid p, A arg);
    public R visit(cpp.Absyn.TChar p, A arg);
    public R visit(cpp.Absyn.TQCon p, A arg);

  }

}
