package cpp.Absyn; // Java Package generated by the BNF Converter.

public class TRef extends RType {
  public final RType rtype_;
  public TRef(RType p1) { rtype_ = p1; }

  public <R,A> R accept(cpp.Absyn.RType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof cpp.Absyn.TRef) {
      cpp.Absyn.TRef x = (cpp.Absyn.TRef)o;
      return this.rtype_.equals(x.rtype_);
    }
    return false;
  }

  public int hashCode() {
    return this.rtype_.hashCode();
  }


}
