package cpp.Absyn; // Java Package generated by the BNF Converter.

public abstract class Var implements java.io.Serializable {
  public abstract <R,A> R accept(Var.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(cpp.Absyn.VarDecl p, A arg);
    public R visit(cpp.Absyn.VarInit p, A arg);

  }

}
