package cpp.Absyn; // Java Package generated by the BNF Converter.

public class DUsing extends Def {
  public final ListId listid_;
  public DUsing(ListId p1) { listid_ = p1; }

  public <R,A> R accept(cpp.Absyn.Def.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof cpp.Absyn.DUsing) {
      cpp.Absyn.DUsing x = (cpp.Absyn.DUsing)o;
      return this.listid_.equals(x.listid_);
    }
    return false;
  }

  public int hashCode() {
    return this.listid_.hashCode();
  }


}
