package cpp.Absyn; // Java Package generated by the BNF Converter.

public class EQCon extends Exp {
  public final ListId listid_;
  public EQCon(ListId p1) { listid_ = p1; }

  public <R,A> R accept(cpp.Absyn.Exp.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof cpp.Absyn.EQCon) {
      cpp.Absyn.EQCon x = (cpp.Absyn.EQCon)o;
      return this.listid_.equals(x.listid_);
    }
    return false;
  }

  public int hashCode() {
    return this.listid_.hashCode();
  }


}
