package cpp.Absyn; // Java Package generated by the BNF Converter.

public abstract class RType implements java.io.Serializable {
  public abstract <R,A> R accept(RType.Visitor<R,A> v, A arg);
  public interface Visitor <R,A> {
    public R visit(cpp.Absyn.TPType p, A arg);
    public R visit(cpp.Absyn.TRef p, A arg);

  }

}
