package cpp.Absyn; // Java Package generated by the BNF Converter.

public class TConst extends Type {
  public final RType rtype_;
  public TConst(RType p1) { rtype_ = p1; }

  public <R,A> R accept(cpp.Absyn.Type.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof cpp.Absyn.TConst) {
      cpp.Absyn.TConst x = (cpp.Absyn.TConst)o;
      return this.rtype_.equals(x.rtype_);
    }
    return false;
  }

  public int hashCode() {
    return this.rtype_.hashCode();
  }


}
