package cpp.Absyn; // Java Package generated by the BNF Converter.

public class TPType extends RType {
  public final PType ptype_;
  public TPType(PType p1) { ptype_ = p1; }

  public <R,A> R accept(cpp.Absyn.RType.Visitor<R,A> v, A arg) { return v.visit(this, arg); }

  public boolean equals(Object o) {
    if (this == o) return true;
    if (o instanceof cpp.Absyn.TPType) {
      cpp.Absyn.TPType x = (cpp.Absyn.TPType)o;
      return this.ptype_.equals(x.ptype_);
    }
    return false;
  }

  public int hashCode() {
    return this.ptype_.hashCode();
  }


}
